### ISSUE TITLE
tareas de prueba

### ISSUE THREAD

**Issue by ProyectoTeam5** [ProyectoTeam5/Egg_Proyect#15]
confirmen si les llega la notificacion de esta tarea 
1 @Dorysfer 
2 @eduardomartsanch 
3 @Gustavoxmv 
4 @JesusNjo 
5 @marioRobledo37 
6 @PaoSotomayor
7  @ErickArrebol
8  @LaureanoCid 
9 @Camila-Saucedo23

**Comment by Dorysfer** [comment]
Sí, llegó por acá

**Comment by LaureanoCid** [comment]
Aca no llego nada

**Comment by sanjuandevmx** [comment]
La tarea llego por aca!
